// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy3T9sHxpjgUUKmq3xg_Rv41_F-ps_ffI',
    appId: '1:472947874974:web:1476a7023b69d833deaf8f',
    messagingSenderId: '472947874974',
    projectId: 'vibe-c564d',
    authDomain: 'vibe-c564d.firebaseapp.com',
    storageBucket: 'vibe-c564d.appspot.com',
    measurementId: 'G-BJ6D5JX016',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvYSYfgHPmX_a4lQvXqdNY27QwvMEFHS4',
    appId: '1:472947874974:android:e39afe8689773135deaf8f',
    messagingSenderId: '472947874974',
    projectId: 'vibe-c564d',
    storageBucket: 'vibe-c564d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABkRLetM8t8OmLs9OpJxtuN4DWok0Wb4Y',
    appId: '1:472947874974:ios:10c90aa54330811bdeaf8f',
    messagingSenderId: '472947874974',
    projectId: 'vibe-c564d',
    storageBucket: 'vibe-c564d.appspot.com',
    iosBundleId: 'vibeapp.com.vibe',
  );
}
